-- raw biomarker firehose — reviewed tsdb migration (source of truth).
-- Origin: generated by @timescaledb/core (see timeseries/generated/raw_biomarker.sql),
-- reviewed + modernized to the current WITH-clause hypertable API. Applied by
-- timeseries/migrate.ts; statements split on `-- statement-breakpoint`.
--
-- Narrow-table shape: one row per sample. Adding one of the "130 biomarkers" is a new
-- metric value (whitelisted app-side via zod), not a DDL change.

CREATE TABLE raw_biomarker (
  ts        timestamptz      NOT NULL,
  user_id   text             NOT NULL,
  device_id text             NOT NULL,
  metric    text             NOT NULL,
  value     double precision NOT NULL
) WITH (
  tsdb.hypertable,
  tsdb.partition_column = 'ts',
  tsdb.chunk_interval = '7 days'
);

-- statement-breakpoint

-- dedupe guard (must include the partition column). Paired with the deterministic
-- sample generator, ON CONFLICT DO NOTHING makes re-ingest of any window a no-op.
-- Doubles as the (user, metric, time-range) read-path index.
CREATE UNIQUE INDEX raw_biomarker_dedupe_idx
  ON raw_biomarker (user_id, metric, ts, device_id);
