-- hourly + daily rollups — reviewed tsdb migration (source of truth).
-- Origin: generated by @timescaledb/core (see timeseries/generated/biomarker_1h.sql /
-- biomarker_1d.sql), reviewed with one deliberate change: materialized_only = false
-- (real-time aggregates) so a live device sync shows up in bucketed charts instantly
-- instead of waiting for the refresh policy. (Since TimescaleDB 2.13 the default is
-- materialized-only.) CREATE MATERIALIZED VIEW ... WITH (timescaledb.continuous)
-- cannot run inside a transaction — the runner applies each statement separately.

CREATE MATERIALIZED VIEW biomarker_1h
WITH (timescaledb.continuous, timescaledb.materialized_only = false) AS
SELECT
  time_bucket('1 hour', ts) AS bucket,
  user_id,
  metric,
  avg(value)      AS avg_value,
  min(value)      AS min_value,
  max(value)      AS max_value,
  count(*)::bigint AS sample_count
FROM raw_biomarker
GROUP BY bucket, user_id, metric
WITH NO DATA;

-- statement-breakpoint

SELECT add_continuous_aggregate_policy('biomarker_1h',
  start_offset      => INTERVAL '3 days',
  end_offset        => INTERVAL '1 hour',
  schedule_interval => INTERVAL '15 minutes');

-- statement-breakpoint

CREATE MATERIALIZED VIEW biomarker_1d
WITH (timescaledb.continuous, timescaledb.materialized_only = false) AS
SELECT
  time_bucket('1 day', ts) AS bucket,
  user_id,
  metric,
  avg(value)      AS avg_value,
  min(value)      AS min_value,
  max(value)      AS max_value,
  count(*)::bigint AS sample_count
FROM raw_biomarker
GROUP BY bucket, user_id, metric
WITH NO DATA;

-- statement-breakpoint

SELECT add_continuous_aggregate_policy('biomarker_1d',
  start_offset      => INTERVAL '30 days',
  end_offset        => INTERVAL '1 day',
  schedule_interval => INTERVAL '1 hour');
