// dev-time generator: emits @timescaledb/core's SQL for the tsdb schema into
// generated/ as REFERENCE output. run: bun run tsdb:generate
//
// deliberately NOT a live migrator — the committed files under migrations/ are the
// reviewed source of truth (design-controls stance: DDL ships as a reviewed artifact,
// no library mutates the schema at runtime). the reviewed files modernize the output
// to the current columnstore-era API and fix generator quirks (e.g. 0.0.1 emits
// double-quoted option values in the compression ALTER, which postgres reads as
// identifiers), which is exactly why the review step exists.

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { biomarker1d, biomarker1h, rawBiomarkerHypertable } from './ddl';

const outDir = join(import.meta.dir, 'generated');

const banner = (title: string) =>
  `-- GENERATED by @timescaledb/core 0.0.1 via timeseries/generate.ts — reference only.\n-- The reviewed, committed migration lives in timeseries/migrations/. Do not apply this file.\n-- ${title}\n\n`;

await mkdir(outDir, { recursive: true });

await writeFile(
  join(outDir, 'raw_biomarker.sql'),
  banner('hypertable (up)') +
    rawBiomarkerHypertable.up().build() +
    '\n\n-- down --\n' +
    rawBiomarkerHypertable.down().build() +
    '\n',
);

for (const [name, cagg] of [
  ['biomarker_1h', biomarker1h],
  ['biomarker_1d', biomarker1d],
] as const) {
  const up = cagg.up();

  await writeFile(
    join(outDir, `${name}.sql`),
    banner(`continuous aggregate ${name} (up)`) +
      up.build() +
      '\n\n' +
      (up.getRefreshPolicy() ?? '-- no refresh policy') +
      '\n\n-- down --\n' +
      cagg.down().build().join('\n') +
      '\n',
  );
}

console.log(`tsdb reference SQL written to ${outDir}`);
